added styles for text
isaevad/OrganicFood pull request #4
Opened 2023-01-16 17:43 UTC by isaevad

2023-01-18 05:23 UTC, AigerimYerk requested changes
В целом неплохо. Надо разобраться с цветами, почему-то все цвета неправильные.

2023-01-18 05:23 UTC, AigerimYerk commented on index.html
> +  <head>
Есть лишние отступы

2023-01-18 05:23 UTC, AigerimYerk commented on index.html
> +          </a></li>
Закрывающие тэги li надо перенести на новую строчку

2023-01-18 05:23 UTC, AigerimYerk commented on index.html
> +            <img src="">
не указан путь к картинке

2023-01-18 05:23 UTC, AigerimYerk commented on index.html
> +          </p>
убрать перенос на новую строку закрывающего тэга </p>

2023-01-18 05:23 UTC, AigerimYerk commented on index.html
> +        <li></li>
Для чего стоит пустой li?

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#343434
Не хватает пробела после color: и точки с запятой на конце строки

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#343434
та же ошибка

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  font-weight: 400;
Если вы уберете эти 3 строчки что-то изменится? Нужны ли они?

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#343434
не указали высоту строки 24px

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#343434;
снова не хватает пробела, указан другой цвет

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  font-size: 48px;
не задан нужный цвет span и для p, который находятся внутри div с классом benefits

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +.subtitle {
Если стили для классов subtitle и title одинаковые, то можно объединить стили чтобы не было повторов стилей, указав селекторы через запятую:
.title, .subtitle {
  font-family: 'Rosario';
  font-size: 70px;
  line-height: 90px;
  font-weight: 700;
}

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  font-weight: 700;
не указан правильный цвет шрифта

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#343434;
Возможно, у вас не настроена фигма, из-за этого получился другой цвет

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +  color:#858585
точка с запятой

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +.ahmed {
странное название класса😅 скорее всего это имя клиента, который оставил отзыв

2023-01-18 05:23 UTC, AigerimYerk commented on css/style.css
> +.footer {
лучше все-таки дать название footer-nav, с таким названием класса легко спутать с самим футером

2023-01-18 05:27 UTC, isaevad commented
Здравствуйте, спасибо за проверку. Все цвета брала с фигмы, тоже думала что-то слишком все серое, посмотрю сегодня--Отправлено из мобильной Яндекс Почты18.01.2023, 11:23, "Aigerim Yerkabayeva" ***@***.***>:
@AigerimYerk requested changes on this pull request.

В целом неплохо. Надо разобраться с цветами, почему-то все цвета неправильные.

In index.html:
> -            <div>
-              <img src="img/star.svg">
-              <p>20K</p>
-              <p>Reviews</p>
-            </div>
-            <div>
-              <img src="img/harvest.svg">
-              <p>300</p>
-              <p>Items</p>
-            </div>
-          </div>
-        </section>
-        <section>
-          <h2>Why We Are The Best?</h2>
-          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley...</p>
+  <head>  

Есть лишние отступы



In index.html:
> +  <head>  
+    <title>Organicfood</title>
+    <meta charset="UTF-8">
+    <link href="css/style.css" rel="stylesheet">
+  </head>
+  <body>
+    <header>
+      <ul class="header-nav">
+        <li><a href="#">About Us</a></li>
+        <li><a href="#">Service</a></li>
+        <li><a href="#">Menu</a></li>
+        <li><a href="#">Contact</a></li>
+        <li>
+          <a href="#">
+            <img src="/img/planet-earth.svg" width="56" height="56">
+          </a></li>

Закрывающие тэги li надо перенести на новую строчку



In index.html:
> +        </li>
+        <li>
+          <a href="#">
+            <img src="img/Buy.svg">
+          </a></li>
+        <li><a href="#">Register Now</a></li>
+      </ul>
+    </header>
+    <main>
+      <section>
+        <h1 class="title">Organic Fruit and Vegetables</h1>
+        <div>
+          <p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley...</p>
+          <a href="#" class="order">
+            <p>Order Now</p>
+            <img src="">

не указан путь к картинке



In index.html:
> +          <a href="#">
+            <img src="img/App Storeeng.png">
+          </a>
+        </div>
+      </section>
+    </main>
+    <footer>
+      <ul class="footer">
+        <li>
+          <a href="#">
+            <img src="/img/planet-earth.svg">
+          </a>
+        </li> 
+        <li>
+          <p class="description">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer...
+          </p>

убрать перенос на новую строку закрывающего тэга 



In index.html:
> +      <ul class="footer">
+        <li>Navigation</li>
+        <li><a href="#">About Us</a></li>
+        <li><a href="#">Service</a></li>
+        <li><a href="#">Menu</a></li>
+      </ul>
+      <ul class="footer">
+        <li>Resources</li>
+        <li><a href="#">Reviews</a></li>
+        <li><a href="#">Blog</a></li>
+        <li><a href="#">Update News</a></li>
+      </ul>
+      <ul class="footer">
+        <li>Contact Us</li>
+        <li><a href="#">Email: ***@***.***</a></li>
+        <li></li>

Для чего стоит пустой li?



In css/style.css:
> +}
+
***@***.*** {
+  font-family: 'Rosario';
+  src: url(/fonts/Rosario-Bold.ttf);
+  font-weight: 700;
+}
+
+body {
+  font-family: 'DMSans';
+  font-size: 18px;
+  line-height: 30px;
+  font-weight: 400;
+  padding: 0;
+  margin: 0;
+  color:#343434

Не хватает пробела после color: и точки с запятой на конце строки



In css/style.css:
> +  font-family: 'DMSans';
+  font-size: 18px;
+  line-height: 30px;
+  font-weight: 400;
+  padding: 0;
+  margin: 0;
+  color:#343434
+}
+
+.header-nav {
+  list-style-type: none;
+}
+
+.header-nav a {
+  text-decoration: none;
+  color:#343434

та же ошибка



In css/style.css:
> +
+.header-nav a {
+  text-decoration: none;
+  color:#343434
+}
+
+.title {
+  font-family: 'Rosario';
+  font-size: 70px;
+  line-height: 90px;
+  font-weight: 700;
+}
+
+.description {
+  color: #858585;
+  font-weight: 400;

Если вы уберете эти 3 строчки что-то изменится? Нужны ли они?



In css/style.css:
> +  font-family: 'Rosario';
+  font-size: 70px;
+  line-height: 90px;
+  font-weight: 700;
+}
+
+.description {
+  color: #858585;
+  font-weight: 400;
+  font-size: 18px;
+  line-height: 30px;
+}
+
+.order {
+  font-weight: 500;
+  color:#343434;

снова не хватает пробела, указан другой цвет



In css/style.css:
> +
+.description {
+  color: #858585;
+  font-weight: 400;
+  font-size: 18px;
+  line-height: 30px;
+}
+
+.order {
+  font-weight: 500;
+  color:#343434;
+  text-decoration: none;
+}
+
+.benefits span {
+  font-size: 48px;

не задан нужный цвет span и для p, который находятся внутри div с классом benefits



In css/style.css:
> +  font-size: 18px;
+  line-height: 30px;
+}
+
+.order {
+  font-weight: 500;
+  color:#343434;
+  text-decoration: none;
+}
+
+.benefits span {
+  font-size: 48px;
+  line-height: 48px;
+}
+
+.subtitle {

Если стили для классов subtitle и title одинаковые, то можно объединить стили чтобы не было повторов стилей, указав селекторы через запятую:
.title, .subtitle {
font-family: 'Rosario';
font-size: 70px;
line-height: 90px;
font-weight: 700;
}



In css/style.css:
> +}
+
+.header-nav {
+  list-style-type: none;
+}
+
+.header-nav a {
+  text-decoration: none;
+  color:#343434
+}
+
+.title {
+  font-family: 'Rosario';
+  font-size: 70px;
+  line-height: 90px;
+  font-weight: 700;

не указан правильный цвет шрифта



In css/style.css:
> +  font-size: 70px;
+  font-weight: 700;
+  line-height: 90px;
+}
+
+.plus {
+  font-family: 'DMSans';
+  font-size: 20px;
+  line-height: 30px;
+  font-weight: 700;
+}
+
+.aside {
+  font-size: 14px;
+  line-height: 20px;
+  color:#858585

точка с запятой



In css/style.css:
> +}
+
+.plus {
+  font-family: 'DMSans';
+  font-size: 20px;
+  line-height: 30px;
+  font-weight: 700;
+}
+
+.aside {
+  font-size: 14px;
+  line-height: 20px;
+  color:#858585
+}
+
+.ahmed {

странное название класса😅 скорее всего это имя клиента, который оставил отзыв



In css/style.css:
> +  font-weight: 700;
+}
+
+.aside {
+  font-size: 14px;
+  line-height: 20px;
+  color:#858585
+}
+
+.ahmed {
+  font-weight: 500;
+  font-size: 30px;
+  line-height: 36px;
+}
+
+.footer {

лучше все-таки дать название footer-nav, с таким названием класса легко спутать с самим футером



In css/style.css:
> +  font-family: 'DMSans';
+  font-size: 18px;
+  line-height: 30px;
+  font-weight: 400;
+  padding: 0;
+  margin: 0;
+  color:#343434
+}
+
+.header-nav {
+  list-style-type: none;
+}
+
+.header-nav a {
+  text-decoration: none;
+  color:#343434

не указали высоту строки 24px



In css/style.css:
> +  font-family: 'Rosario';
+  font-size: 70px;
+  line-height: 90px;
+  font-weight: 700;
+}
+
+.description {
+  color: #858585;
+  font-weight: 400;
+  font-size: 18px;
+  line-height: 30px;
+}
+
+.order {
+  font-weight: 500;
+  color:#343434;

Возможно, у вас не настроена фигма, из-за этого получился другой цвет

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-20 07:53 UTC, AigerimYerk commented
Хорошая работа👍

2023-01-20 07:54 UTC, AigerimYerk approved these changes

2023-01-20 07:54 UTC, merged